spring.application.name=pakailagi-server

# Server Configuration
server.port=8080

# Konfigurasi file upload (max 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
